name: Sigma Rule Convert

on:
  push:
    branches:
      - lindy/sigma-workflows

permissions:
  contents: read

jobs:
  sigma-rule-convert:
    name: Convert sigma rules to panther rules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OMGWINNING Panter Analysis
        uses: actions/checkout@v4

      - name: Checkout Sigma HQ Codebase rules
        uses: actions/checkout@v4
        with:
          repository: SigmaHQ/sigma
          ref: master
          path: sigma
          fetch-depth: 1

      - name: Checkout Panther Sigma Backend
        uses: actions/checkout@v4
        with:
          repository: panther-labs/pySigma-backend-panther
          path: pysigma-backend-panther

      - name: Set python version
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.11"
                  
      - name: Verify Python version
        run: python --version

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify Poetry version
        run: poetry --version

      - name: Install dependencies
        run: | 
          cd pysigma-backend-panther
          poetry install

      - name: Run the conversion script agaisnt sigma rules
        run: |
          mkdir rules/sigma_rules/
          cd pysigma-backend-panther
          poetry run  sigma convert --skip-unsupported -t panther -f default ../sigma/rules -O output_dir=../rules/sigma_rules/
        continue-on-error: true

      - name: Run the conversion script agaisnt sigma rules emerging threats
        run: |
          cd pysigma-backend-panther
          poetry run  sigma convert --skip-unsupported -t panther -f default ../sigma/rules-emerging-threats -O output_dir=../rules/sigma_rules/
        continue-on-error: true

      - name: Run the conversion script agaisnt sigma rules threat hunting
        run: |
          cd pysigma-backend-panther
          poetry run  sigma convert --skip-unsupported -t panther -f default ../sigma/rules-threat-hunting -O output_dir=../rules/sigma_rules/
        continue-on-error: true

      - name: Validate the converted rules
        run: |
          ls -la rules/sigma_rules/
          ls -la rules/

      - name: Set up Git user
        run: |
          git config --global user.email "github-service-account-automation@panther.io"
          git config --global user.name "panther-bot-automation"

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.PANTHER_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PANTHER_BOT_GPG_PRIVATE_KEY_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          
      - name: Update Repo with latest Sigma Rules
        run: |
          git add rules/sigma_rules/
          git status
          git commit -m "Update Sigma Rules with latest changes" --gpg-sign
          git push origin HEAD:update-sigma-rules-${GITHUB_RUN_ID}

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     token: ${{ secrets.PANTHER_BOT_AUTOMATION_TOKEN }}
      #     commit-message: "Update Airflow with latest Panther Analysis changes"
      #     title: "Update Airflow with latest Panther Analysis changes"
      #     body: "Automated update from Panther Analysis repository"
      #     branch: "update-airflow-${GITHUB_RUN_ID}"
      #     base: "main"
      #     path: "destination"