name: Sigma Rule Convert

on:
  push:
    branches:
      - lindy/sigma-workflows

permissions:
  contents: read

jobs:
  sigma-rule-convert:
    name: Convert sigma rules to panther rules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sigma HQ Codebase rules
        uses: actions/checkout@v4
        with:
          repository: SigmaHQ/sigma
          ref: master
          path: sigma
          fetch-depth: 1

      - name: Checkout Panther Sigma Backend
        uses: actions/checkout@v4
        with:
          repository: panther-labs/pySigma-backend-panther
          path: pysigma-backend-panther

      - name: List root directory
        run: ls -la

      - name: Set python version
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.11"
                  
      - name: Verify Python version
        run: python --version

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify Poetry version
        run: poetry --version

      - name: Install dependencies
        run: | 
          cd pysigma-backend-panther
          poetry install

      - name: Run the conversion script
        run: |
          cd pysigma-backend-panther
          poetry run  sigma convert -s -t panther -f default ../sigma/rules -O output_dir=../testrules/
          ls -la ../testrules/

     